name: WildLoaders
version: 0.2.0-Beta
api-version: 1.13
main: com.bgsoftware.wildloaders.WildLoadersPlugin
description: Highly configurable and optimized chunk-loaders plugin.
website: https://bg-software.com/
authors: [Ome_R]
commands:
  loader:
    description: Main command for wild loaders.
permissions:
  wildloaders.*:
    description: Gives access to all the commands.
    default: op
    children:
      wildloaders.use: true
      wildloaders.give: true
      wildloaders.list: true
  wildloaders.use:
    description: Gives access to place a chunkloader.
  wildloaders.give:
    description: Gives access to give chunkloaders to other players.
  wildloaders.list:
    description: Gives access to see all the available chunk loaders.